CrisD3v/LiberFit-PF

client/src/components/Atoms/Inputs/AddButton/AddButton.tsx
client/src/components/Atoms/Inputs/CreateInput/CreateInput.tsx
client/src/components/Atoms/Inputs/DescriptionInput/DescriptionInput.tsx
client/src/components/Atoms/Inputs/ImageInput/ImageInput.tsx
client/src/components/Atoms/Inputs/SelectInput/SelectInput.tsx
client/src/components/Molecules/CreateInputsContainer/CreateInputsContainer.tsx
client/src/components/Organisms/CreateForm/CreateForm.tsx
client/src/components/Organisms/CreateForm/data.json
client/src/components/Templates/DashboardTemplate/DashboardTemplate.tsx
client/tailwind.config.cjs

Cree los formularios de creación

Maquetado de formularios de creación

---

client/src/components/Molecules/LoginForm/LoginForm.tsx
client/src/components/Molecules/LoginSignup/LoginSignup.tsx

cambio de colores e idioma en español

registro y iniciar sesion

---

client/src/App/Action/Action.ts
client/src/App/FeatureSlices/Users/Users.ts
client/src/App/Store.ts

falta pasar endpoint de get y post users

avanze de action users

---

client/package-lock.json
client/src/components/Molecules/LoginSignup/LoginSignup.tsx

solamente falta agregar toast al alert en parte del registro

avanze de registro

---

client/package-lock.json
client/package.json
client/src/components/Molecules/LoginForm/LoginForm.tsx
client/src/components/Organisms/SideBar/SideBar.tsx
client/src/main.tsx

agregue nuevas lineas para mostrar info de perfil ya se si viene por logeo de base de datos o por cuenta google, se instalo npm auht0, quedaria mandar la info de google al back, ahora cuando el back me devuelva un token, medicaré para q no sea condicional.

arreglo de 3ro

---

api/src/Routes/client.js
client/src/App/Action/Action.ts
client/src/components/Atoms/Perfil/Perfil.tsx
client/src/components/Molecules/LoginForm/LoginForm.tsx
client/src/components/Organisms/SideBar/SideBar.tsx

tarea terminado solo falta probar en cada uno de nosotros y listo

login y 3ro listo

---

client/src/components/Molecules/LoginForm/LoginForm.tsx
client/src/components/Organisms/SideBar/SideBar.tsx

linea nueva de cookie.set() y a la hora de remover tambien

agregue cookie

---

api/src/controllers/paymentControllers.js

Hola Cris por favor acepta cambios

Cambios en payment

---

client/src/components/Atoms/Perfil/ItemsPefil/Items.tsx
client/src/components/Organisms/SideBar/SideBar.tsx

linea que es para que cuando cierre sesion se quede en /home esto es de manera local, y agregue una linea en item que es para mostrar que rol tiene ese usario en este caso se veria como cliente

agregue linea en sidebar

---

api/index.js
api/src/Models/Subscription.js
api/src/Routes/client.js
api/src/Routes/payment.js
api/src/controllers/clientControllers.js
api/src/controllers/gym.json
api/src/db.js
api/src/services/clientServices.js
api/src/services/paymentServices.js

Actualización de modelo y registro de payment y clients y suscription

Actualización back 2.0

---

api/index.js
api/src/Routes/Anuncio.js
api/src/Routes/client.js
api/src/Routes/exercise.js
api/src/Routes/product.js

Reparacion de ruta excirse

---

client/src/components/Organisms/DashboardSections/Admin/Content/DashHome.tsx

agregue algunas lineas para mas info

adelanto dash admin

---

api/src/Models/Anuncios.js
api/src/Models/Locacion.js
api/src/Models/Training.js

Atributo agregado

---

api/src/Routes/client.js
api/src/controllers/clientControllers.js
client/src/App/Action/Action.ts
client/src/App/FeatureSlices/Data/Data.ts
client/src/components/Molecules/DashboardTables/UsersTable.tsx

avanze delete

---

client/src/App/Action/Action.ts
client/src/App/FeatureSlices/Data/Data.ts
client/src/components/Molecules/DashboardTables/UsersTable.tsx

cambie algunas cosas para que marce arregle la tabla

modificar linea

---

api/src/Routes/training.js

Actualizacion de envio de correo

Actualizancion de envio de correo

---

client/src/App/Action/Action.ts

agregue lineas para el dash admin

actions para el dash admin

---

api/src/config/nodemailer.js

Fixed Bug nodemailer

---

client/package-lock.json
client/package.json
client/src/components/Molecules/LoginForm/LoginForm.tsx
client/src/components/Molecules/LoginSignup/LoginSignup.tsx
client/src/components/Organisms/SideBar/SideBar.tsx

instale libreria sweetalert2 para dar estilos

cambio de alert

---

client/src/components/Molecules/NavForm/NavForm.tsx

moví la función cerrar sesión del sidebar al nav

copie y pegue en navar el confirmar cerrar sesion

---

api/src/Routes/employe.js
api/src/controllers/employeControllers.js
api/src/services/employeServices.js
client/src/components/Molecules/CreateInputsContainer/EmployeeForm/EmployeeForm.tsx
client/src/components/Molecules/DashboardTables/UsersTable.tsx
client/src/components/Organisms/DashboardSections/Admin/Content/DashEmpleados.tsx

Agregamos lineas para delete y post de empleados y clients

para matii pureba

---

api/src/Routes/client.js
api/src/Routes/employe.js
api/src/Routes/gym.js
api/src/Routes/location.js
api/src/Routes/training.js
api/src/controllers/gymControllers.js
api/src/services/gymServices.js
client/src/App.tsx
client/src/App/Action/Action.ts
client/src/App/FeatureSlices/Data/Data.ts
client/src/components/Molecules/Contrase/Contrase.tsx
client/src/components/Molecules/CreateInputsContainer/EmployeeForm/EmployeeForm.tsx
client/src/components/Molecules/CreateInputsContainer/LocacionForm/LocacionForm.tsx
client/src/components/Molecules/CreateInputsContainer/trainingsForm/trainingsForm.tsx
client/src/components/Molecules/DashboardTables/LocationsTable.tsx
client/src/components/Molecules/DashboardTables/TrainingsTable.tsx
client/src/components/Molecules/DashboardTables/UsersTable.tsx
client/src/components/Molecules/LoginForm/LoginForm.tsx
client/src/components/Organisms/DashboardSections/Admin/Content/DashEmpleados.tsx
client/src/components/Organisms/DashboardSections/Admin/Content/DashLocations.tsx
client/src/components/Organisms/DashboardSections/Admin/Content/DashTrainings.tsx

agregue nunvas funcionalidaes al dash admin en sus tablas

Arreglo de conflictos

---

api/src/controllers/gym.json
api/src/services/initializeData.js
client/src/components/Molecules/CardCategory/CardsCategory.tsx
client/src/components/Molecules/CreateInputsContainer/EmployeeForm/EmployeeForm.tsx
client/src/components/Molecules/CreateInputsContainer/LocacionForm/LocacionForm.tsx
client/src/components/Molecules/DashboardTables/PaymentsTable.tsx
client/src/components/Molecules/DashboardTables/UsersTable.tsx
client/src/components/Molecules/DetailComponents/MachineDetails/MachineDetails.tsx
client/src/components/Molecules/DetailComponents/ProductsDetails/ProductsDetails.tsx
client/src/components/Molecules/DetailComponents/TrainingsDetails/TrainingsDetails.tsx
client/src/components/Molecules/Plan/Plan.tsx

Fixed Bugs, styles, references

Fixed Bugs, styles, references
